import "./global.css"

import localFont from "next/font/local"

const Noto_Sans_KR = localFont({
  src: [
    { path: "../fonts/NotoSansKR-Thin.woff2", weight: "100", style: "normal" },
    { path: "../fonts/NotoSansKR-ExtraLight.woff2", weight: "200", style: "normal" },
    { path: "../fonts/NotoSansKR-Light.woff2", weight: "300", style: "normal" },
    { path: "../fonts/NotoSansKR-Regular.woff2", weight: "400", style: "normal" },
    { path: "../fonts/NotoSansKR-Medium.woff2", weight: "500", style: "normal" },
    { path: "../fonts/NotoSansKR-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../fonts/NotoSansKR-Bold.woff2", weight: "700", style: "normal" },
    { path: "../fonts/NotoSansKR-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "../fonts/NotoSansKR-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-NotoSansKR",
  display: "swap",
  preload: true,
})

export const metadata = {
  title: "Welcome to publishing",
  description: "Generated by create-nx-workspace",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={Noto_Sans_KR.className}>
      <body>{children}</body>
    </html>
  )
}
